name: 'Changelog Reader'
description: 'Read and parse the CHANGELOG.md file of the project'
branding:
  icon: 'align-right'
  color: 'gray-dark'
inputs:
  path:
    description: 'Path to the CHANGELOG.md file containing the log entries'
    required: false
    default: './CHANGELOG.md'
  version:
    description: 'Version of the log entry wanted'
    required: false
outputs:
  version:
    description: 'The release version. Ex...2.0.0.'
  date:
    description: 'The release date. Ex...2020-08-22.'
  status:
    description: 'The status of the release is one of the following: prereleased, released, unreleased, or yanked.'
  changes:
    description: 'All the changes defined for that release.'
runs:
  using: 'node12'
  main: 'dist/index.js'
