name: 'Changelog Reader'
description: 'Read and parse the CHANGELOG.md file of the project'
branding:
  icon: 'align-right'
  color: 'gray-dark'
inputs:
  path:
    description: 'Path to the CHANGELOG.md file containing the log entries'
    required: false
    default: './CHANGELOG.md'
  version:
    description: 'Version of the log entry wanted'
    required: false
outputs:
  log_entry:
    description: 'The log entry wanted. Defaults to the last release on the CHANGELOG.md file if version is not specified'
runs:
  using: 'node12'
  main: 'dist/index.js'
