name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Changelog Entry
      uses: ./
      id: changelog_reader
      with:
        milliseconds: 1000
        version: v1.0.1 
    - run: echo ${{ steps.changelog_reader.outputs.log_entry }}
